// Generated by gencpp from file demo03/demo01srv.msg
// DO NOT EDIT!


#ifndef DEMO03_MESSAGE_DEMO01SRV_H
#define DEMO03_MESSAGE_DEMO01SRV_H

#include <ros/service_traits.h>


#include <demo03/demo01srvRequest.h>
#include <demo03/demo01srvResponse.h>


namespace demo03
{

struct demo01srv
{

typedef demo01srvRequest Request;
typedef demo01srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct demo01srv
} // namespace demo03


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::demo03::demo01srv > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::demo03::demo01srv&) { return value(); }
};

template<>
struct DataType< ::demo03::demo01srv > {
  static const char* value()
  {
    return "demo03/demo01srv";
  }

  static const char* value(const ::demo03::demo01srv&) { return value(); }
};


// service_traits::MD5Sum< ::demo03::demo01srvRequest> should match
// service_traits::MD5Sum< ::demo03::demo01srv >
template<>
struct MD5Sum< ::demo03::demo01srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::demo03::demo01srv >::value();
  }
  static const char* value(const ::demo03::demo01srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo03::demo01srvRequest> should match
// service_traits::DataType< ::demo03::demo01srv >
template<>
struct DataType< ::demo03::demo01srvRequest>
{
  static const char* value()
  {
    return DataType< ::demo03::demo01srv >::value();
  }
  static const char* value(const ::demo03::demo01srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::demo03::demo01srvResponse> should match
// service_traits::MD5Sum< ::demo03::demo01srv >
template<>
struct MD5Sum< ::demo03::demo01srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::demo03::demo01srv >::value();
  }
  static const char* value(const ::demo03::demo01srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo03::demo01srvResponse> should match
// service_traits::DataType< ::demo03::demo01srv >
template<>
struct DataType< ::demo03::demo01srvResponse>
{
  static const char* value()
  {
    return DataType< ::demo03::demo01srv >::value();
  }
  static const char* value(const ::demo03::demo01srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEMO03_MESSAGE_DEMO01SRV_H
